---
include:
  - template: Security/Secret-Detection.gitlab-ci.yml

  - project: renovate-bot/renovate-runner
    file: /templates/renovate-config-validator.gitlab-ci.yml

stages:
  - test

shellcheck:
  stage: test
  image: koalaman/shellcheck-alpine:v0.10.0
  script:
    - |
      shellcheck tmux-cssh
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - tmux-cssh

shfmt:
  stage: test
  image: mvdan/shfmt:v3.9.0-alpine
  script:
    - |
      shfmt -d -l -i 2 -ci tmux-cssh
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - tmux-cssh
